---

# Open edX Native installation for single server community installs.

- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    EDXAPP_PREVIEW_LMS_BASE: EDXAPP_LMS_BASE
    EDXAPP_LOGIN_REDIRECT_WHITELIST: [ "{{ EDXAPP_CMS_BASE }}" ]
    EDXAPP_LMS_BASE_SCHEME: http
    EDXAPP_LMS_NGINX_PORT: '80'

##### Modifs par EDULIB 20190207
    repo_edulib: "EDUlib"
    version_edulib: "edulib-ironwood.1rc1"

    CERTS_REPO: 'https://github.com/{{ repo_edulib }}/edx-certificates.git'
    certs_version: "{{ version_edulib }}"
    edx_ansible_source_repo: 'https://github.com/{{ repo_edulib }}/configuration.git'
    configuration_version: "{{ version_edulib }}" 
    edx_platform_repo: 'https://github.com/{{ repo_edulib }}/edx-platform.git'
    edx_platform_version: "{{ version_edulib }}"
    forum_source_repo: 'https://github.com/{{ repo_edulib }}/cs_comments_service.git'
    forum_version: "{{ version_edulib }}"
    NOTIFIER_SOURCE_REPO: 'https://github.com/{{ repo_edulib }}/notifier.git'
    NOTIFIER_VERSION: "{{ version_edulib }}" 
    xqueue_source_repo: 'https://github.com/{{ repo_edulib }}/xqueue.git'
    xqueue_version: "{{ version_edulib }}"
    XQUEUE_VERSION: "{{ version_edulib }}"
    ECOMMERCE_VERSION: "{{ version_edulib }}"
    ECOMMERCE_WORKER_VERSION: "{{ version_edulib }}"
    DISCOVERY_VERSION: "{{ version_edulib }}"
    demo_version: "{{ version_edulib }}"
    INSIGHTS_VERSION: "{{ version_edulib }}"
    ANALYTICS_API_VERSION: "{{ version_edulib }}"
    THEMES_VERSION: "{{ version_edulib }}"
##### Modifs par EDULIB 20190207

    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: True
    DISCOVERY_URL_ROOT: 'http://localhost:{{ DISCOVERY_NGINX_PORT }}'
    COMMON_ENABLE_AWS_ROLE: false
    ecommerce_create_demo_data: true
    credentials_create_demo_data: true
    SANDBOX_ENABLE_DISCOVERY: true
    SANDBOX_ENABLE_ECOMMERCE: true
    SANDBOX_ENABLE_ANALYTICS_API: true
    SANDBOX_ENABLE_INSIGHTS: true
    SANDBOX_ENABLE_RABBITMQ: true
    JOURNALS_ENABLED: false
  roles:
    - role: swapfile
      SWAPFILE_SIZE: 4GB
    - role: aws
      when: COMMON_ENABLE_AWS_ROLE
    - role: nginx
      nginx_sites:
      - certs
      - cms
      - lms
      - forum
      - xqueue
      nginx_default_sites:
      - lms
    - role: edxlocal
      when: EDXAPP_MYSQL_HOST == 'localhost'
    - role: memcache
      when: "'localhost' in ' '.join(EDXAPP_MEMCACHE)"
    - role: mongo_3_2
      when: "'localhost' in EDXAPP_MONGO_HOSTS"
    - role: rabbitmq
      rabbitmq_ip: 127.0.0.1
      when: SANDBOX_ENABLE_RABBITMQ
    - role: edxapp
      celery_worker: True
    - edxapp
##### Installed separately at EDUlib
#####    - role: ecommerce
#####      when: SANDBOX_ENABLE_ECOMMERCE
#####    - role: ecomworker
#####      ECOMMERCE_WORKER_BROKER_HOST: 127.0.0.1
#####      when: SANDBOX_ENABLE_ECOMMERCE
##### Installed separately at EDUlib
    - role: analytics_api
      when: SANDBOX_ENABLE_ANALYTICS_API
    #- role: insights
    #  when: SANDBOX_ENABLE_INSIGHTS
    # not ready yet: - edx_notes_api
    - analytics_api
    - demo
    # not ready yet: - edx_notes_api
##### Installed separately at EDUlib
#    - oauth_client_setup
##### Installed separately at EDUlib
    - oraclejdk
    - role: elasticsearch
      when: "'localhost' in EDXAPP_ELASTIC_SEARCH_CONFIG|map(attribute='host')"
    - forum
    #- role: discovery
    #  when: SANDBOX_ENABLE_DISCOVERY
    #- role: journals
    #  when: JOURNALS_ENABLED
    - role: notifier
      NOTIFIER_DIGEST_TASK_INTERVAL: 5
    - role: xqueue
      update_users: True
    - certs
    - edx_ansible
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: postfix_queue
      when: POSTFIX_QUEUE_EXTERNAL_SMTP_HOST != ''
    - role: datadog-uninstall
      when: not COMMON_ENABLE_DATADOG
