- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    migrate_db: 'yes'
    openid_workaround: true
    EDXAPP_LMS_NGINX_PORT: '80'
    EDX_ANSIBLE_DUMP_VARS: true
    CERTS_DOWNLOAD_URL: 'https://edulib-certificats.s3.amazonaws.com'
    CERTS_VERIFY_URL: 'http://ec2-52-2-47-62.compute-1.amazonaws.com:18090'
    # used for releases
    edx_platform_version: 'OPENEDX_RELEASE'
    certs_version: 'OPENEDX_RELEASE'
    forum_version: 'OPENEDX_RELEASE'
    xqueue_version: 'OPENEDX_RELEASE'
  roles:
    - edx_ansible
    - user
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      - xqueue
      - certs
      nginx_default_sites:
      - lms
      - cms
    - edxlocal
    - mongo
    - edxapp
    - { role: 'edxapp', celery_worker: True }
    - demo
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - oraclejdk
    - elasticsearch
    - forum
    - { role: "xqueue", update_users: True }
    - certs
    - role: analytics_api
      when: ANALYTICS_API_GIT_IDENTITY
    - edx_ansible
